version: "3.9"

services:
  database:
    image: postgis/postgis:16-3.4
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
